const ACCOUNT_STATE = {
    UNVERIFIED: 'UNVERIFIED',
    VERIFIED: "VERIFIED",
    BANNED: "BANNED",
}

const BUTTON_STATE = {
    DISABLE: 'DISABLE',
    ENABLE: 'ENABLE',
    PENDING: 'PENDING',
    DONE:'DONE',
    REJECTED: 'REJECTED'
}

const ITEM_STATE = {
    CREATED: 'CREATED',
    LISTING: 'LISTING',
    SOLD: 'SOLD',
    DELIVERED: 'DELIVERED',
    CANCELED: 'CANCELED',
    HIDDEN: 'HIDDEN',
}

const LISTING_STATE = {
    BUY_NOW: 'BUY_NOW',
    START_SOON: 'START_SOON',
    ACTIVE: 'ACTIVE',
    ENDED: 'ENDED',
}

export {
    BUTTON_STATE,
    ACCOUNT_STATE,
    ITEM_STATE,
    LISTING_STATE,
}
